# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b8f68feed9b728e147e8468e20ac505b21e71576c7329f6e8e7ffa344440d0843ecdbbfa2af472c0a6c92d219ee61f6229d4f492310dc92f0fa5134c977e01f

test:
  secret_key_base: 340cf63c5f1ae9d1ec3befe407939b7a8002f93eeed3f640cf51682f5301cc6ef1d4d9b14985a89ec9dad5df4df8d6456da50fbb2f9b28dc5622ec589a798b2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
